Fix: code drift

diff --git a/resource/in b/resource/in
--- a/resource/in
+++ b/resource/in
@@ -8,38 +8,55 @@ set_log_prefix "resource/check"
 SCRIPT_INPUT='/tmp/input'
 cat > $SCRIPT_INPUT <&0 # STDIN params
 
-LOCAL_PATH=/mnt/storage
-
+MANIFEST_PATH=$(mktemp /mnt/storage/resource-samba.manifest.XXXXXX)
+ARCHIVE_PATH=$(mktemp /mnt/storage/resource-samba.archive.XXXXXX)
 VERSION=$(jq -r '.version.ref // ""' < $SCRIPT_INPUT)
-
 SMB_SERVER=$(jq -r '.source.server // ""' < $SCRIPT_INPUT)
 SMB_SHARE=$(jq -r '.source.share // ""' < $SCRIPT_INPUT)
-SMB_PATHS=$(jq -r '.source.paths // ""' < $SCRIPT_INPUT)
+SMB_MANIFEST=$(jq -r '.source.manifest[] // []' < $SCRIPT_INPUT)
 SMB_USER=$(jq -r '.source.user // ""' < $SCRIPT_INPUT)
 SMB_PASSWORD=$(jq -r '.source.password // ""' < $SCRIPT_INPUT)
 
-log "status" "  localPath:" $LOCAL_PATH
+log "build" "src_dir: " $SRC_DIR
+log "build" "build_id: " $BUILD_ID
+log "build" "build_name: " $BUILD_NAME
+log "build" "build_job_name: " $BUILD_JOB_NAME
+log "build" "build_pipeline_name: " $BUILD_PIPELINE_NAME
+log "build" "atc_external_url: " $ATC_EXTERNAL_URL
+
+log "status" "   manifest:" $MANIFEST_PATH
+log "status" "    archive:" $ARCHIVE_PATH
 log "status" "    version:" $VERSION
 log "status" "       user:" $SMB_USER
 log "status" "   password:" $SMB_PASSWORD
 log "status" "     server:" $SMB_SERVER
 log "status" "      share:" $SMB_SHARE
-log "status" "       path:" $SMB_PATH
+log "status" "   manifest:" $SMB_MANIFEST
 log "status" "    pattern:" $SMB_PATTERN
 
-smb_get $SMB_SERVER $SMB_SHARE $SMB_PATH $SMB_PATTERN $SMB_USER $SMB_PASSWORD $LOCAL_PATH
+#
+# Validation
+#
+[ -n "$VERSION" ] || abort "ERROR Version specifiation $VERSION invalid!"
 
-# echo $DIR 1>&2
-# echo ${#REFS} 1>&2
+#
+# Check Resource
+# - dump manifest array to file
+smb_create_manifest $SMB_MANIFEST[@] $MANIFEST_PATH
 
-# NEW_REF="{ \"ref\": \"$DIR\" }"
-# if [ "${#REFS}" != "0" ]; then
-#   NEW_REF="{ \"ref\": \"$DIR\" },"
-# fi
+# - fetch remote files as archive
+smb_get $SMB_SERVER $SMB_SHARE $ARCHIVE_PATH $MANIFEST_PATH $SMB_USER $SMB_PASSWORD
 
-# REFS=$NEW_REF$REFS # See the concat
+#
+# Response
+# - generate hash
+HASH=$(smb_generate_hash $ARCHIVE_PATH)
+echo $HASH
+if [ "$HASH" = "$VERSION" ]; then
+  break
+fi
 
-# if [ "$DIR" = "$VERSION" ]; then
-#   break
-# fi
+if [ "$HASH" != "$VERSION" ]; then
+	success "{ \"ref\": \"${HASH}\" }"
+fi
 
diff --git a/resource/lib/smb b/resource/lib/smb
--- a/resource/lib/smb
+++ b/resource/lib/smb
@@ -55,7 +55,18 @@ smb_put () {
 
 }
 
-hash () {
+smb_create_manifest () {
+	([ -n "${1}" ]) \
+		&& map=$1 \
+		|| abort "missing map"
+	([ -n "${2}" ]) \
+		&& target=$2 \
+		|| abort "missing target file"
+
+	printf "%s\n" "${map}" > $target
+}
+
+smb_generate_hash () {
 	PLATFORM=`uname`
 	MD5_TOOL="md5sum"
 	if [ $PLATFORM = "Darwin" ]; then
